In [1]:
import numpy as np

In [6]:
arr = np.array([1,0,3])
copyArr = arr.astype(bool)
print(copyArr)

[ True False  True]


In [8]:
x = arr.copy()
x[0] = 22
arr[0] = 21
print(arr)
print(x)

[21  0  3]
[22  0  3]


In [9]:
arr.view()

array([21,  0,  3])

In [10]:
arr[0] = 90
arr.view()

array([90,  0,  3])

In [11]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [15]:
arr = np.array([1, 2, 3, 4], ndmin = 4)

print(arr.shape)

(1, 1, 1, 4)


In [16]:
print(arr)

[[[[1 2 3 4]]]]


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,0])

newarr = arr.reshape(3, 3)

print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.base)
print((arr.reshape(2, 4)).base)

None
[1 2 3 4 5 6 7 8]


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,0])

newarr = arr.reshape(3, 3, -1)
print(newarr)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [0]]]


In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)


[1 2 3 4 5 6]


In [34]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [35]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
