In [1]:
'''
ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.

ufuncs also take additional arguments, like:
where boolean array or condition defining where the operations should take place.
dtype defining the return type of elements.
out output array where the return value should be copied.


'''



'\nufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.\n\nufuncs also take additional arguments, like:\nwhere boolean array or condition defining where the operations should take place.\ndtype defining the return type of elements.\nout output array where the return value should be copied.\n\n\n'

In [2]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [3]:
x = [1,2,3,4,5]
y = (12,34,54,4,665)
z = []

for i, j in zip(x,y):
    z.append(i+j)
print(z)

[13, 36, 57, 8, 670]


In [10]:
# creating ufunc
import numpy as np

def myadd(a, b):
    return a+b

myadd = np.frompyfunc(myadd,2,1)

print(myadd([1,2,3,4], [5,6,7,8]))
print(type(myadd))

[6 8 10 12]
<class 'numpy.ufunc'>


In [16]:
# arithmatic operations
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.multiply(arr1, arr2))
print(np.divide(arr1, arr2))

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
print(np.power(arr1, arr2))

print(np.mod(arr1, arr2))

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
newarr = np.divmod(arr1, arr2)
print(newarr)

[30 32 34 36 38 40]
[-10 -10 -10 -10 -10 -10]
[200 231 264 299 336 375]
[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]
[          1000     1280000000 19683000000000  6553600000000
           2500              0]
[ 1  6  3  0  0 27]
(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [17]:
arr = np.array([-1, -2, 1, 2, 3, -4])
newarr = np.absolute(arr)
print(newarr)

[1 2 1 2 3 4]


In [20]:
# Rounding Decimals
# truncation -> fix
# rounding -> rounds of deciaml value
# floor
# ceil

arr = np.trunc([-3.221324, 3.2324])
print(arr)

arr = np.around(3.1666, 2) # to the 2nd deciaml value
print(arr)

arr = np.floor([-3.1666, 3.6667])
print(arr)

arr = np.ceil([-3.1666, 3.6667])
print(arr)

[-3.  3.]
3.17
[-4.  3.]
[-3.  4.]


In [22]:
# Logs -> NumPy provides functions to perform log at the base 2, e and 10.
arr = np.arange(1,10)
print(np.log2(arr))
print(np.log10(arr))

# log base e
arr = np.arange(1, 10)
print(np.log(arr))


[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [26]:
# Summation -> sum of all elements in n no. of arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

print(np.sum([arr1, arr2]))

# to sum over an axis we do 
print(np.sum([arr1, arr2], axis=1))


12
[6 6]


In [28]:
'''Cummulative Sum
Cummulative sum means partially adding the elements in array.

E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].
'''

arr = np.array([1, 2, 3, 4])
print(np.cumsum(arr))

[ 1  3  6 10]


In [33]:
# numpy products
arr = np.array([1, 2, 3, 4])
print(np.prod(arr))

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
print(np.prod([arr1, arr2], axis = 1))

# cumulative product
print(np.cumprod(arr1))

24
[  24 1680]
[ 1  2  6 24]


In [36]:
# differences
arr = np.array([10, 15, 25, 5])
print(np.diff(arr))
print(np.diff(arr, n = 2))


[  5  10 -20]
[  5 -30]


In [40]:
# Finding LCM (Lowest Common Multiple)
print(np.lcm(4, 6))

print(np.lcm.reduce([3,6,9,12]))

arr = np.arange(1,11)
print(np.lcm.reduce(arr))

12
36
2520


In [ ]:
# Finding GCD (Greatest Common Divisor)
num1 = 6
num2 = 9

x = np.gcd(num1, num2)
print(x)

print(np.gcd.reduce([10,24,28]))

3


In [59]:
# Trigonometric Functions
print(np.sin(np.pi/2))
arr = np.array([np.pi/2, np.pi/3, np.pi/4])
print(np.sin(arr))

# degree -> radian
arr = np.array([90, 60, 45, 30, 0])
print(np.deg2rad(arr))

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x = np.rad2deg(arr)
print(x)

print(np.arcsin(1.0))

arr = np.array([1, -1, 0.1])
print(np.arcsin(arr))

# hypoteneous
perp = 3
base = 4
print(np.hypot(perp, base))

1.0
[1.         0.8660254  0.70710678]
[1.57079633 1.04719755 0.78539816 0.52359878 0.        ]
[ 90. 180. 270. 360.]
1.5707963267948966
[ 1.57079633 -1.57079633  0.10016742]
5.0


In [60]:
# Hyperbolic functions
print(np.sinh(np.pi/2))

2.3012989023072947


In [61]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
print(np.cosh(arr))

[2.50917848 1.60028686 1.32460909 1.20397209]


In [62]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
print(np.arcsinh(arr))

[1.23340312 0.91435666 0.72122549 0.5929557 ]


In [71]:
# Set Operation
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
print(np.unique(arr))

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
print(np.union1d(arr1, arr2))

print(np.intersect1d(arr1, arr2, assume_unique = True))
print(np.setdiff1d(arr1, arr2))

print(np.setxor1d(arr1, arr2, assume_unique=True))

[1 2 3 4 5 6 7]
[1 2 3 4 5 6]
[3 4]
[1 2]
[1 2 5 6]
